language: android
android:
    components:
        # Android SDK tools
        - tools
        - platform-tools
        
        # Build tools
        - build-tools-28.0.0
        
        # SDK version used to compile project
        - android-28
        
        # Additional components
        - extra-google-google_play_services