language: android
jdk: oraclejdk8

android:
    components:
        # Android SDK tools
        - tools
        - platform-tools
        
        # Build tools
        - build-tools-28.0.0
        
        # SDK version used to compile project
        - android-28
        
        # Additional components
        - extra-google-google_play_services
        - extra-android-support
        
        - sys-img-armeabi-v7a-android-26
        
env:
    matrix:
        - "ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a"
        
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution
    
cache:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache